import "../styles/globals.css";
import "../styles/fanta.css";
import Head from './head'
import AuthProvider from "@/context/AuthContext";

export const metadata = {
  title: "MDNOTES | Easy Breezy Notetaking",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head />
      <AuthProvider>
        <body>
          <div id="app">{children}</div>
          <div id="portal"></div>
        </body>
      </AuthProvider>
    </html>
  );
}
